/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Mood = IDL.Text;
export const Recipe = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'emoji' : IDL.Text,
  'moodTags' : IDL.Vec(Mood),
  'prepTime' : IDL.Nat,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllRecipes' : IDL.Func([], [IDL.Vec(Recipe)], ['query']),
  'getFavorites' : IDL.Func([], [IDL.Vec(Recipe)], ['query']),
  'getRecipesByMood' : IDL.Func([Mood], [IDL.Vec(Recipe)], ['query']),
  'register' : IDL.Func([], [], []),
  'toggleFavorite' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Mood = IDL.Text;
  const Recipe = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'emoji' : IDL.Text,
    'moodTags' : IDL.Vec(Mood),
    'prepTime' : IDL.Nat,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllRecipes' : IDL.Func([], [IDL.Vec(Recipe)], ['query']),
    'getFavorites' : IDL.Func([], [IDL.Vec(Recipe)], ['query']),
    'getRecipesByMood' : IDL.Func([Mood], [IDL.Vec(Recipe)], ['query']),
    'register' : IDL.Func([], [], []),
    'toggleFavorite' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };